<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.handyplus.region</groupId>
    <artifactId>ip2region</artifactId>
    <version>2.4.1</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spigot-api.vesion>1.21.11-R0.1-SNAPSHOT</spigot-api.vesion>
        <annotations.version>26.0.2</annotations.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>${spigot-api.vesion}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>${annotations.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <distributionManagement>
        <repository>
            <id>handy-repository</id>
            <url>https://nexus.handyplus.cn/releases</url>
        </repository>
    </distributionManagement>

    <build>
        <plugins>
            <!--指定1.8jdk-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <release>8</release>
                    <compilerArgs>
                        <arg>-Xlint:-options</arg>
                        <arg>-Xlint:-removal</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <!-- 源代码插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.4.0</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- Javadoc插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.12.0</version>
                <configuration>
                    <!-- 使用的Java版本 -->
                    <source>8</source>
                    <!-- 禁用严格检查 -->
                    <doclint>none</doclint>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- 发布到额外的 Maven 仓库 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.1.4</version>
                <executions>
                    <execution>
                        <id>deploy-aliyun</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                        <configuration>
                            <!--阿里云效-->
                            <altDeploymentRepository>
                                handy::https://packages.aliyun.com/60bf16902c5969c370c5f508/maven/handy
                            </altDeploymentRepository>
                        </configuration>
                    </execution>
                    <execution>
                        <id>deploy-handyplus-maven</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                        <configuration>
                            <!-- 腾讯CNB -->
                            <altDeploymentRepository>
                                handyplus-maven::https://maven.cnb.cool/handyplus/maven/-/packages/
                            </altDeploymentRepository>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>